# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MailtrapCli < Formula
  desc "CLI for the Mailtrap email delivery platform"
  homepage "https://github.com/mailtrap/mailtrap-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.1.1/mailtrap-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "a9799c816832ccaa61631adf799704e6f93ff3e28ce3791c0eecfe4cfbc4a27f"

      define_method(:install) do
        bin.install "mailtrap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.1.1/mailtrap-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "c4f7c80a2d2d75e4d14ee208dd22b0d3480d598ff4bafe4bff4aaea54db4d77a"

      define_method(:install) do
        bin.install "mailtrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.1.1/mailtrap-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "0988ae0dd9a35bba7b58af1e87aad6db38fbb47e1ceed54ee63d39f7c9661c99"
      define_method(:install) do
        bin.install "mailtrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.1.1/mailtrap-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "8ba371e1096939846116e25557cbeaf1a906cea92595e3a15b40e53875118f19"
      define_method(:install) do
        bin.install "mailtrap"
      end
    end
  end

  test do
    system "#{bin}/mailtrap", "--help"
  end
end
