# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailtrap < Formula
  desc "CLI for the Mailtrap email delivery platform"
  homepage "https://github.com/mailtrap/mailtrap-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.1.2/mailtrap-cli_0.1.2_darwin_amd64.tar.gz"
      sha256 "cf4dee714cc6d241ef7814f4d8856347e051cedfdae84a799aa3baefe41362a2"

      define_method(:install) do
        bin.install "mailtrap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.1.2/mailtrap-cli_0.1.2_darwin_arm64.tar.gz"
      sha256 "899e65cf03878e8e50a75ba9aac7e74a39c20fa8893e106520efaf4dfc0c9f35"

      define_method(:install) do
        bin.install "mailtrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.1.2/mailtrap-cli_0.1.2_linux_amd64.tar.gz"
      sha256 "b67e131451f39293c1ba09d186c1505d423faa93c020826124a612801881b05c"
      define_method(:install) do
        bin.install "mailtrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.1.2/mailtrap-cli_0.1.2_linux_arm64.tar.gz"
      sha256 "be178e8a33c1a278c5cb786d3c7fb1a6712f90031407826c1d5e78233126dd77"
      define_method(:install) do
        bin.install "mailtrap"
      end
    end
  end

  test do
    system "#{bin}/mailtrap", "--help"
  end
end
