# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailtrap < Formula
  desc "CLI for the Mailtrap email delivery platform"
  homepage "https://github.com/mailtrap/mailtrap-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.3.0/mailtrap-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "0400ed1266b328ccff6ed210478b10dc2da76ddd9c879985d4d0433fc1eca9a1"

      define_method(:install) do
        bin.install "mailtrap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.3.0/mailtrap-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "18386ecaa88bca7f317c70f68c899e5e62ae21d9d9896c7bd4ad37ee490a8ccf"

      define_method(:install) do
        bin.install "mailtrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.3.0/mailtrap-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "936e82de3ca2b3a2f7ecbf5f47dbc15cce14bd2505c930aa39c15a4b223598db"
      define_method(:install) do
        bin.install "mailtrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtrap/mailtrap-cli/releases/download/v0.3.0/mailtrap-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "4a5058ff23fbd0d7bfe9c9eceb02eb692046913daa8c679996778bf3616618b7"
      define_method(:install) do
        bin.install "mailtrap"
      end
    end
  end

  test do
    system "#{bin}/mailtrap", "--help"
  end
end
